#:schema node_modules/wrangler/config-schema.json
name = "multerize-workers-test"
main = "src/index.ts"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'test'